PDCpy enhancement
hpc-io/PDCpy pull request #8
Opened 2024-11-08 15:57 UTC by zhangwei217245

1. Positional args for check_type to support multiple types
2. Avoid conflicting between multiple ranks for ctrace
3. disable_ctrace
4. add bytes, list, dict, pickle support for metadata attributes

2024-11-14 18:32 UTC, houjun requested changes

2024-11-14 18:32 UTC, houjun commented on pdc/object.pyx
> +                    print(f"shape of out: {out.shape}")
Can you comment out this debug print?

2024-11-14 18:32 UTC, houjun commented on pdc/object.pyx
> +            print(f"sizes: {sizes}, object.dims: {object.dims}")
Can you comment out this debug print?

2024-12-12 19:09 UTC, zhangwei217245 commented on pdc/object.pyx
> +                    print(f"shape of out: {out.shape}")
fixed.

2024-12-12 19:09 UTC, zhangwei217245 commented on pdc/object.pyx
> +            print(f"sizes: {sizes}, object.dims: {object.dims}")
fixed.

2024-12-12 19:09 UTC, zhangwei217245 commented
I would like to remind that the aforementioned debugging logs are commented out. we can go ahead and merge the PR.

2024-12-16 23:49 UTC, houjun approved these changes

2024-12-16 23:49 UTC, merged